format_version: 2
environments:
  ci:
    pipelines:
      - "team3UI"

pipelines:
  "team3UI":
    group: team3
    materials:
      ui:
        git: "git@github.com:nayanikadey/cricket-scorer-ui-nobackend.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn install
                    yarn run ci
      - build:
          jobs:
            build:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn install
                    yarn run build
      - deploy:
          jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    sh ./buildAndDeploy/deploy.sh team3-bootcamp-august2018
